### ISSUE TITLE
go-support – tasks

### ISSUE THREAD

**Issue by marcellanz** [marcellanz/cloudstate#2]
- [ ] go:generate protobufs
- [ ] define how *.proto files come to (_these_) language support repositories (influences the developer flow)
- [ ] move go-support into a separate repository (go import has ideas how this is laid out; go-import metatag. Alternatives? => mirror cloudstate/go-support/ into something usable, check how others do it... even travis has no good story for that)
- [ ] this should make the godoc story easier to solve
- [ ] revise packages... depends how go import name is structured => keep it flat
- [ ] define how to build cloudstate with a certain language support library => see also https://github.com/cloudstateio/cloudstate/issues/7, see also build.sbt task buildGoTCKShoppingCart
- [ ] decide package base for go-support => cloudstate.io/cloudstate vs. github.com/cloudstateio/gosupport
- [ ] think about Behaviours from the Java API
- [ ] complete and test snapshots
- [ ] tests
- [ ] events and snapshot marshalers other than (gob, json, ...) see also https://github.com/cloudstateio/cloudstate/issues/25
- [ ] complete docs/../user/lang/go
- [ ] CRDTs
- [ ] functions.proto
- [ ] implement the chat application and deliver a docker image for it
- [ ] having "code snipped validation" (see https://github.com/cloudstateio/cloudstate/issues/104 and https://github.com/cloudstateio/cloudstate/blob/master/docs/src/test/java/docs/user/gettingstarted/ShoppingCartMain.java#L4-L16)
- [ ] implement https://cloudstate.io/docs/user/lang/java/serialization.html

**Comment by marcellanz** [comment]
superfluous, all issues are tracked on https://github.com/cloudstateio/go-support
